# Site settings
remote_theme: cnorick/jekyll-theme-easy-wedding
#theme: jekyll-theme-easy-wedding
title: Amanda & Brianna
#email:
url: "https://www.brimanda.com"
description: "We're getting married and can't wait to celebrate with you!"
#baseurl: /


collections:
  stories:
    sort_by: order
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      type: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml
